image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    # https://www.gitpod.io/docs/prebuilds#github-specific-configuration
    branches: true
tasks:
  - name: Setup npm
    init: npm i -g npm@7 && gp sync-done npm
  - name: Setup node
    init: gp sync-await npm && nvm install && nvm use && nvm alias default 14
